language: node_js
sudo: true
node_js:
- 6.11.5
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - github.com
  - bitbucket.org
before_install:
- npm install -g npx
- npm install -g pm2
- bash ./.travis/scripts/init.sh
- bash ./.travis/scripts/clone.sh
script:
- npm run build
- bash ./.travis/scripts/deploy.sh
branches:
  only:
  - master
  - dev
  - release
env:
  global:
    secure: l/s/sMZ1uUBgFsyLEfhK23/s0WnMLk7SeYspaqbnjUHZQqIRQKZfpg4xGPugdd069GuMgYnC0d7UJhaarvF+6xLcwVzHrgXN4kWOTtnTg8PKW956QjOa8yT9J+iaLHf8UIqpu0l0HE5SWGO9mgqlf81/6xWkx/GVfjTwOvuNoRMByYmaVCFh77R/7u9xrhASSxQDYnwYdzl6TmNyBj+mLIRuUUsIjs2e/jAQR5rf8OeE7kFPIjjAdoTnjbyDWhAiCsMr4wN0EUBswUZ9RO6awcIkuAuuJR24kcnmL+ysDGR6byj/nCy4e4gdnmm52iCHPu32kEP/4+1hnBiM4wz3iTw/qUB37I+h7BSGyZHt3P+MwLM9EKS5oGVfl9YUiB5ELRpPuS24ly/8mVtKuUrd13bLso4t0Ruo3q/KnfG2/aHpYJ2ZQ7zTIckrXSXOcBeXbhE8JZyqm0XSwGYL1mgPgUpVX+2EAsVSTHFg1vQgKG6k7kvuUzriFnTfgSGrsq3Qga46Bh+MphDPBadVGLSj/JGGBraaD0wEyeVnybu3ybCsg8lzcM5TWuWlAY4nUVGQYa1JrN6KT2BNhE9orD0YW3kP0kVeEtdyditR//Z4MmOwvn/HbrKhzdI1UjVoL3UlG+FEf8C1N6WEr7dP+/1Sp3RyGuvGM2Tx3tecC6rzh+s=
